name: Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  NODE_VERSION_FILE: .nvmrc

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm ci

      - name: Get Tag Name
        uses: ./.github/actions/get-tag-name
        id: get-tag-name
      - name: Create Tag
        uses: actions/github-script@v3
        env:
          TAG: '${{ steps.get-tag-name.outputs.tag-name }}'
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.get-tag-name.outputs.tag-name }}",
              sha: context.sha
            })
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag-name.outputs.tag-name }}
          release_name: 'v${{ steps.get-tag-name.outputs.tag-name }}'
          body: '${{github.event.pull_request.body}}'
          draft: false
          prerelease: false
