name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - run: bash ./scripts/ci/echo-npmrc.sh ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/
      - run: bash ./scripts/ci/echo-npmrc.sh ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: npm ci
      - run: npm run build:package
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
